apiVersion: v1
kind: Service
metadata:
  name: {{ include "tm.api" . }}
  labels:
    {{- include "tm.labels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "tm.selector" (dict "ctx" . "component" "api") | nindent 4 }}
  ports:
    - name: {{ include "tm.scheme" . }}
      port: {{ .Values.api.port }}
      targetPort: {{ include "tm.scheme" . }}
      protocol: TCP
