{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tm.api" . }}
  labels:
    {{- include "tm.labels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.api.minAvailable }}
  selector:
    matchLabels:
      {{- include "tm.selector" (dict "ctx" . "component" "api") | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tm.web" . }}
  labels:
    {{- include "tm.labels" (dict "ctx" . "component" "web") | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.web.minAvailable }}
  selector:
    matchLabels:
      {{- include "tm.selector" (dict "ctx" . "component" "web") | nindent 6 }}
{{- end }}
