apiVersion: v1
kind: Service
metadata:
  name: {{ include "tm.web" . }}
  labels:
    {{- include "tm.labels" (dict "ctx" . "component" "web") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "tm.selector" (dict "ctx" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
