/**
 * Every error code the API can return, dotted lowercase.
 *
 * Derived from docs/DOMAIN.md, docs/API_CONVENTIONS.md (core codes and the
 * `<entity>.not.found`, `<entity>.<op>.failed`, `<entity>.conflict` conventions) and the
 * current factories in api/src/lib/errors/domains. These values must be checked against the
 * API once its migration to the dotted format is complete.
 */
export const ErrorCodes = {
  AuthInvalidCredentials: 'auth.invalid.credentials',
  AuthLoginFailed: 'auth.login.failed',
  AuthLogoutFailed: 'auth.logout.failed',
  AuthMeFailed: 'auth.me.failed',
  AuthMicrosoftFailed: 'auth.microsoft.failed',
  AuthMicrosoftRejected: 'auth.microsoft.rejected',
  AuthMicrosoftUnavailable: 'auth.microsoft.unavailable',
  AuthMicrosoftUnknownUser: 'auth.microsoft.unknown.user',
  AuthRefreshFailed: 'auth.refresh.failed',
  AuthSessionInvalid: 'auth.session.invalid',
  ClockConflict: 'clock.conflict',
  ClockCreateFailed: 'clock.create.failed',
  ClockCurrentFailed: 'clock.current.failed',
  ClockDeleteFailed: 'clock.delete.failed',
  ClockInFailed: 'clock.in.failed',
  ClockInvalid: 'clock.invalid',
  ClockListFailed: 'clock.list.failed',
  ClockNotFound: 'clock.not.found',
  ClockOutFailed: 'clock.out.failed',
  ClockOverlap: 'clock.overlap',
  ClockRetrieveFailed: 'clock.retrieve.failed',
  ClockUpdateFailed: 'clock.update.failed',
  CryptoDecryptFailed: 'crypto.decrypt.failed',
  CryptoKeyInvalid: 'crypto.key.invalid',
  DuplicateKey: 'duplicate.key',
  InternalUnexpected: 'internal.unexpected',
  JsonInvalid: 'json.invalid',
  LogCreateFailed: 'log.create.failed',
  RateLimitExceeded: 'rate.limit.exceeded',
  ReportInvalid: 'report.invalid',
  ReportTeamFailed: 'report.team.failed',
  ReportTeamNotFound: 'report.team.not.found',
  ReportUserFailed: 'report.user.failed',
  RouteNotFound: 'route.not.found',
  TeamArchiveFailed: 'team.archive.failed',
  TeamCreateFailed: 'team.create.failed',
  TeamDeleteFailed: 'team.delete.failed',
  TeamListFailed: 'team.list.failed',
  TeamManagerInvalid: 'team.manager.invalid',
  TeamMemberAddFailed: 'team.member.add.failed',
  TeamMemberListFailed: 'team.member.list.failed',
  TeamMemberNotFound: 'team.member.not.found',
  TeamMemberRemoveFailed: 'team.member.remove.failed',
  TeamMemberTeamArchived: 'team.member.team.archived',
  TeamMemberTeamNotFound: 'team.member.team.not.found',
  TeamMemberUserArchived: 'team.member.user.archived',
  TeamMemberUserNotFound: 'team.member.user.not.found',
  TeamNotFound: 'team.not.found',
  TeamRestoreFailed: 'team.restore.failed',
  TeamRetrieveFailed: 'team.retrieve.failed',
  TeamScheduleInvalid: 'team.schedule.invalid',
  TeamUpdateFailed: 'team.update.failed',
  TokenAuthenticationFailed: 'token.authentication.failed',
  Unauthorized: 'unauthorized',
  UserArchiveFailed: 'user.archive.failed',
  UserConflict: 'user.conflict',
  UserCreateFailed: 'user.create.failed',
  UserDeleteFailed: 'user.delete.failed',
  UserListFailed: 'user.list.failed',
  UserNotFound: 'user.not.found',
  UserPasswordInvalid: 'user.password.invalid',
  UserRestoreFailed: 'user.restore.failed',
  UserRetrieveFailed: 'user.retrieve.failed',
  UserUpdateFailed: 'user.update.failed',
  ValidationError: 'validation.error',
} as const;

/** Union of every known API error code. */
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
