variable "postgres_instances" {
  description = "Number of CloudNativePG instances (one primary plus replicas). Production runs 3 so a node loss keeps a synchronous-capable quorum; kind may use 1."
  type        = number
  default     = 3

  validation {
    condition     = var.postgres_instances >= 1 && var.postgres_instances <= 9 && floor(var.postgres_instances) == var.postgres_instances
    error_message = "postgres_instances must be an integer from 1 to 9."
  }
}

variable "postgres_database" {
  description = "Application database created by initdb."
  type        = string
  default     = "timemanager"

  validation {
    condition     = can(regex("^[a-z_][a-z0-9_]{0,62}$", var.postgres_database))
    error_message = "postgres_database must be a lowercase PostgreSQL identifier (letters, digits, underscore, up to 63 characters)."
  }
}

variable "postgres_owner" {
  description = "Application owner role created by initdb; its password is generated by Terraform and stored in Vault KV secret/databases/postgres."
  type        = string
  default     = "timemanager"

  validation {
    condition     = can(regex("^[a-z_][a-z0-9_]{0,62}$", var.postgres_owner)) && !contains(["postgres", "streaming_replica"], var.postgres_owner)
    error_message = "postgres_owner must be a lowercase PostgreSQL identifier and cannot be postgres or streaming_replica."
  }
}

variable "postgres_image" {
  description = "PostgreSQL operand image, pinned to an exact minor and the same major as the backup image (ops/backup uses postgres 17) so pg_dump and pg_restore match the server."
  type        = string
  default     = "ghcr.io/cloudnative-pg/postgresql:17.11-standard-bookworm"

  validation {
    condition     = can(regex(":[0-9]+\\.[0-9]+", var.postgres_image)) && !endswith(var.postgres_image, ":latest")
    error_message = "postgres_image must carry an exact version tag such as 17.11-standard-bookworm, never latest or a bare major."
  }
}

variable "postgres_storage_class" {
  description = "StorageClass of the data and WAL volumes. Null selects var.storage_class_retain (encrypted, reclaimPolicy Retain): a deleted claim must never delete database volumes."
  type        = string
  default     = null
}

variable "postgres_storage_size" {
  description = "Size of each instance data volume. Grow only: raise the value and apply, the class must allow volume expansion (resizeInUseVolumes is on). Lowering it cannot shrink a PVC and makes the Cluster update fail, so restore into a smaller recovery cluster instead."
  type        = string
  default     = "50Gi"

  validation {
    condition     = can(regex("^[1-9][0-9]*(Gi|Ti)$", var.postgres_storage_size))
    error_message = "postgres_storage_size must be a whole number of Gi or Ti, for example 50Gi."
  }
}

variable "postgres_wal_storage_size" {
  description = "Size of each instance WAL volume (separate PVC so a WAL archiving stall cannot fill the data volume). Grow only, same rules as postgres_storage_size."
  type        = string
  default     = "10Gi"

  validation {
    condition     = can(regex("^[1-9][0-9]*(Gi|Ti)$", var.postgres_wal_storage_size))
    error_message = "postgres_wal_storage_size must be a whole number of Gi or Ti, for example 10Gi."
  }
}

variable "postgres_resources" {
  description = "Requests and limits of the postgres container. Memory request equals the limit (no overcommit on the data pool) and shared_buffers must stay below a quarter of it."
  type = object({
    requests = map(string)
    limits   = map(string)
  })
  default = {
    requests = { cpu = "500m", memory = "2Gi" }
    limits   = { memory = "2Gi" }
  }
}

variable "postgres_parameters" {
  description = "postgresql.conf parameters merged over the tuned defaults (sized for the 2Gi memory limit). password_encryption is always forced to scram-sha-256; parameters owned by CloudNativePG (ssl, archive_mode, wal_level, listen_addresses) are rejected by the operator."
  type        = map(string)
  default = {
    max_connections                     = "200"
    shared_buffers                      = "512MB"
    effective_cache_size                = "1536MB"
    work_mem                            = "8MB"
    maintenance_work_mem                = "128MB"
    wal_compression                     = "on"
    max_wal_size                        = "2GB"
    min_wal_size                        = "512MB"
    checkpoint_timeout                  = "15min"
    checkpoint_completion_target        = "0.9"
    random_page_cost                    = "1.1"
    effective_io_concurrency            = "200"
    idle_in_transaction_session_timeout = "60000"
    hot_standby_feedback                = "on"
    max_standby_streaming_delay         = "60s"
    log_min_duration_statement          = "500"
    log_connections                     = "on"
    log_disconnections                  = "on"
    log_lock_waits                      = "on"
    log_temp_files                      = "0"
    log_checkpoints                     = "on"
    log_autovacuum_min_duration         = "1000"
    track_io_timing                     = "on"
    "pg_stat_statements.max"            = "10000"
    "pg_stat_statements.track"          = "all"
    autovacuum_vacuum_scale_factor      = "0.05"
    autovacuum_analyze_scale_factor     = "0.05"
    tcp_keepalives_idle                 = "60"
    tcp_keepalives_interval             = "10"
    tcp_keepalives_count                = "6"
    jit                                 = "off"
  }
}

variable "postgres_app_client_pod_labels" {
  description = "Labels of the app namespace pods that may open PostgreSQL connections (the api Deployment and its migration Job both carry app.kubernetes.io/name=api). The matching egress policy allow-api-to-postgres lives with the api in app.tf."
  type        = map(string)
  default     = { "app.kubernetes.io/name" = "api" }

  validation {
    condition     = length(var.postgres_app_client_pod_labels) > 0
    error_message = "postgres_app_client_pod_labels cannot be empty: it would admit every pod of the app namespace to the database."
  }
}

variable "postgres_client_certificates_from_vault" {
  description = "Issue the streaming_replica client certificate from the Vault PKI issuer as well (needs a Vault PKI role that accepts the CN streaming_replica). False lets CloudNativePG manage client and replication certificates with its own CA while the server certificate still comes from Vault."
  type        = bool
  default     = true
}

variable "postgres_certificate_duration" {
  description = "Lifetime of the PostgreSQL certificates; the Vault PKI role internal-services caps it at 72h. Renewal starts at one third of the lifetime."
  type        = string
  default     = "48h"

  validation {
    condition     = can(regex("^[1-9][0-9]*h$", var.postgres_certificate_duration))
    error_message = "postgres_certificate_duration must be a whole number of hours such as 48h."
  }
}

variable "eso_cluster_secret_store" {
  description = "Name of the ClusterSecretStore backed by Vault that ExternalSecrets in databases and velero read through."
  type        = string
  default     = "vault"
}
